### 测试管理员注册

GET http://localhost:5173/api/admin?action=register&username=testuser&password=testpass&phone=123&email=345@222&invitationCode=421344
Content-Type: application/json

###

### 测试管理员登录

GET http://localhost:8080/VolunteerManagement_war/api/admin?action=login&username=testuser&password=testpass
Content-Type: application/json

###

### 测试fetch

GET http://localhost:8080/VolunteerManagement_war/api/admin?action=fetch&username=testuser&password=testpass
Content-Type: application/json
###
